before_script:
    - java -version && mvn -v && npm -v && gulp -v
job1:
    script:
        - ./mvnw -Pprod package
        - \cp target/*.war ~/release/fort/
    only:
        - master
    tags:
        - fort
