version: '2'
services:
    fort-mysql:
        container_name: fort-mysql
        image: mysql:5.7.13
        volumes:
            - ~/volumes/fort/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=fort-secret-pw
            - MYSQL_DATABASE=fort
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
